### PR TITLE
Support WindowsServer (windows 10) environments

### LINKED ISSUE #104: Support on WindowsServer
**Describe the bug**
Could not load native library junixsocket-native for architecture amd64-WindowsServer2022

**To Reproduce**
1. make a Github Action
2. use windows-latest or windows-2022, I suppose it is similar to lower versions, see https://github.com/actions/virtual-environments
3. run an app using junixsocket

**Expected behavior**
Sockets work

**Output/Screenshots**
https://github.com/com-lihaoyi/mill/pull/1852#issuecomment-1114332274

**Environment (please complete the following information):**
 - OS: WindowsServer2022
 - windows 10
 - Version 10.0.20348 Build 643

**Notes**
We found a workaround by manually setting `System.setProperty("os.name", "Windows10")`

### PR DESCRIPTION
**Pull request by sake92**
Fixes #104

### CODE REVIEW

**Comment by jvanzyl** [comment]
@sake92 I'm happy to add to your commit if I can get access to your branch. Seems like the addition of  `osName.contains("11")` on line https://github.com/kohlschutter/junixsocket/pull/105/commits/73183b9206a66688acfb0d5f40f6aeb87ed47f2b#diff-72a326e132770acdb4cc0a74ed76a24961962a984e03eb3e31b67b4ea4e6ce0aR316 would get us Windows11 support, yes?

**Comment by sake92** [comment]
@jvanzyl yeah, I suppose. I pushed a commit for win11. To be honest I didn't test the whole build, but it should work.  
It would be good to add some CI tests.

**Comment by jvanzyl** [comment]
I've downloaded Windows10 and 11 so I'll try it here. I'm surprised there aren't Windows10/11 host options available in GitHub Actions given it runs on Azure.

**Comment by sake92** [comment]
Windows Server's 2016..2022 are actually Windows10 based, as far as I can see in their docs.  
Maybe they'll add win11 in the future.
https://github.com/actions/virtual-environments -> https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md

**Review by kohlschuetter — COMMENTED** [review]
There were some minor issues with this PR I commented below.
Since there was some concurrent work done that includes a fix for this bug, this means that we can't merge this PR. However I want you to thank for looking into this!

**Pull request closed without merging**
